filebeat.inputs:
  - type: filestream
    id: squid-access
    enabled: true
    paths:
      - /var/log/squid/access.log*
    parsers:
      - ndjson:
          overwrite_keys: true
          message_key: message
    fields:
      od:
        source: squid
    fields_under_root: true

processors:
  - add_fields:
      target: od
      fields:
        environment: ${OD_ENVIRONMENT:dev}
        service: squid
  - add_host_metadata: ~
  - add_cloud_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
