http_port 3128
icap_enable on
icap_service service_req reqmod_precache icap://icap-adaptor:1344/reqmod bypass=1
adaptation_access service_req allow all

acl all src 0.0.0.0/0
dns_v4_first on
visible_hostname squid
